# Generated by Django 5.1.6 on 2025-02-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='heroes'),
        ),
    ]
